ALTER TABLE users ADD COLUMN "eParchiFee" DECIMAL(10,2) DEFAULT 50;
ALTER TABLE users ADD COLUMN "callConsultationFee" DECIMAL(10,2) DEFAULT 100;
ALTER TABLE users ADD COLUMN "farmVisitFee" DECIMAL(10,2) DEFAULT 500;
