ALTER TABLE users ADD COLUMN "canAdoptCrop" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE users ADD COLUMN "canGiveEPrescription" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE users ADD COLUMN "canTakeCalls" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE users ADD COLUMN "canDoFarmVisits" BOOLEAN NOT NULL DEFAULT false;
